force-app/main/default/objects/Indirect_Issue_Voucher_Event__e/Indirect_Issue_Voucher_Event__e.object-meta.xml
<CustomObject>
    <description>This event is used for  Indirect Issue of Vouchers</description>
    <label>Indirect Issue Voucher Event</label>
    <pluralLabel>Indirect Issue Voucher Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Indirect_Issue_Voucher_Event__e/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <label>Member ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indirect_Issue_Voucher_Event__e/fields/Order_No__c.field-meta.xml
<CustomField>
    <fullName>Order_No__c</fullName>
    <label>Order No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Indirect_Issue_Voucher_Event__e/fields/TotalVouchersToIssue__c.field-meta.xml
<CustomField>
    <fullName>TotalVouchersToIssue__c</fullName>
    <label>TotalVouchersToIssue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/Process_Rewards_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event used as part of Accrual/Purchase process to 1. Issue reward vouchers and 2. Splitting redemption/reward journals</description>
    <label>Process Rewards Event</label>
    <pluralLabel>Process Rewards Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel associated with the Order</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Event type: Issue voucher or split redemption journals</description>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Program_ID__c</fullName>
    <label>Program ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher/fields/Order_Id_Issue__c.field-meta.xml
<CustomField>
    <fullName>Order_Id_Issue__c</fullName>
    <description>Order ID where this voucher has been issued to</description>
    <label>Order Id Issue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher/fields/Order_Id_Issue_Channel__c.field-meta.xml
<CustomField>
    <fullName>Order_Id_Issue_Channel__c</fullName>
    <description>Original channel associated with Order Issue ID</description>
    <label>Order Id Issue Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>POS</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <customValue>
        <fullName>Manual</fullName>
    </customValue>
    <description>Used for capturing channel in Transaction Journal and voucher</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IndirectIssueVoucherEventTriggerHandler.cls
/**
* @name         : IndirectIssueVoucherEventTriggerHandler
* @description  : Handler class for IndirectIssueVoucherEventTrigger
* @testClass    : IndirectIssueVoucherEventTriggerHandlerTest
* <Date>        <Modified By>     	<Brief Description of Change>
* 2024-09-13    Nicholas Then         Created
*/


public class IndirectIssueVoucherEventTriggerHandler extends TriggerHandler {
  
   
    public virtual class IssueVoucherException extends Exception {}  
    
    
    public override void afterInsert() {
        //Subscribe to platform events
        subscribeEvents(Trigger.New);    
    }
    
    //Subscribe to PEs - to  Issue Vouchers 
    private static void subscribeEvents(List<Indirect_Issue_Voucher_Event__e> newEvents){
        System.debug('subscribeEvents >> ' + newEvents);

        List<LoyaltyProcessFlowWrapper.FlowInput> issueVoucherInputs = new List<LoyaltyProcessFlowWrapper.FlowInput>();
         
       
        // Iterate through each event.
        for (Indirect_Issue_Voucher_Event__e event : newEvents) {
            
            LoyaltyProcessFlowWrapper.FlowInput input = new LoyaltyProcessFlowWrapper.FlowInput();
            input.memberId = event.Member_ID__c;
            input.programId = event.Program_ID__c;
            input.orderId = event.Order_No__c;
            input.eventType = event.Event_Type__c;
            input.channel = event.Channel__c;
            input.totalVouchersToIssue = Integer.valueOf(event.TotalVouchersToIssue__c);
            //input.PEreplayId = event.ReplayId;
            //input.PEeventUuid = event.EventUuid;

            issueVoucherInputs.add(input);
            
            
              
            
        }
		System.debug('issueVoucherInputs >> ' + issueVoucherInputs);
		
      
        if (!issueVoucherInputs.isEmpty()) {
            issueRewardVouchers(issueVoucherInputs);
        }

	
    }

 

    //Issue reward vouchers
    private static void issueRewardVouchers(List<LoyaltyProcessFlowWrapper.FlowInput> inputs) {
       
       
             //List<Process_Rewards_Event__e> events = new List<Process_Rewards_Event__e>();
        List<LoyaltyProcessFlowWrapper.FlowOutput> outputs = new List<LoyaltyProcessFlowWrapper.FlowOutput>();
        List<LoyaltyManagement.IssueVoucherInput> issueVoucherList = new List<LoyaltyManagement.IssueVoucherInput>();
       
        for (LoyaltyProcessFlowWrapper.FlowInput rec : inputs) {
            LoyaltyProcessFlowWrapper.FlowOutput output = new LoyaltyProcessFlowWrapper.FlowOutput();
                        
            //Loop through # of vouchers to create
            for(Integer count = 1; count <= rec.totalVouchersToIssue; count++) {

                LoyaltyManagement.IssueVoucherInputBuilder voucher = new LoyaltyManagement.IssueVoucherInputBuilder();
                voucher.setLoyaltyProgramMemberId(rec.memberId);
                voucher.setProgramName(GlobalConstants.LOYALTY_PROGRAM_NAME);
                voucher.setVoucherDefinitionName(GlobalConstants.VOUCHER_DEFINITION_REWARD);
                voucher.setAdditionalNotes(rec.orderId+'@channel@'+rec.channel);
                //voucher.setVoucherCode('Test001');
               //voucher.setJournalId('0lV8r0000000Jx7EAE');

                issueVoucherList.add(voucher.build());
              } 

            outputs.add(output);
        }
        System.debug('issueVoucherList = ' + issueVoucherList);
      
        // Insert vouchers outside the loop
        if (!issueVoucherList.isEmpty()) {
        
            // insert vouchersToInsert;
            List<LoyaltyManagement.IssueVoucherOutput> issueVoucherActionResults = LoyaltyManagement.LoyaltyResources.issueVoucher(issueVoucherList); 
          
             
            System.debug(issueVoucherActionResults);
            System.debug('Issue Voucher Successful Operation:'+ issueVoucherActionResults.get(0));
            Boolean InsertResult = issueVoucherActionResults.get(0).isSuccess();
           
            //throw custom exception if insert failed
            if (!InsertResult){
            throw new IssueVoucherException('Voucher failed to be issued');
                              }
            
            //TODO: Stamp Order ID and Order Item ID against vouchers issued
            List<Id> voucherIds = new List<Id>();
            for(LoyaltyManagement.IssueVoucherOutput rec : issueVoucherActionResults) {
                if (rec.isSuccess()) {
                        voucherIds.add(rec.getVoucherId());
                        } 
            }
            System.debug('voucherIds = ' + voucherIds);
            List<Voucher> vouchersCreated = [SELECT id, Reason  FROM Voucher where id IN:voucherIds];
            List<Voucher> vouchersToUpdate = new List<Voucher>();
            System.debug('processRewardTriggerHandler: vouchersToUpdate = ' + vouchersToUpdate);
            for(Voucher voucherCr : vouchersCreated) {
               String vChannel = voucherCr.Reason.substringAfter('@channel@'); 
               if(!string.isblank(vChannel) && vChannel != 'null'){
                vouchersToUpdate.add( new Voucher(
                    Id = voucherCr.Id,
                    Order_Id_Issue__c = voucherCr.Reason.substringBefore('@channel@'),
                    Order_Id_Issue_Channel__c = voucherCr.Reason.substringAfter('@channel@')
                ));
               } else {
                   vouchersToUpdate.add( new Voucher(
                    Id = voucherCr.Id,
                    Order_Id_Issue__c = voucherCr.Reason.substringBefore('@channel@')
                   
                ));
                   
               }
            }
            System.debug('vouchersToUpdate = ' + vouchersToUpdate);

            if (!vouchersToUpdate.isEmpty()){
                update vouchersToUpdate;
            }
        }
            
            
        

       
    }
    
   
    
    
}