force-app/main/default/objects/Member_Update_Event__e/Member_Update_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event to capture Loyalty Program Member record creation and being updated to notify Wallet Service to re-generate passes.</description>
    <label>Member Update Event</label>
    <pluralLabel>Member Update Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Member_Update_Event__e/fields/Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Member_Id__c</fullName>
    <label>Member Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MemberUpdateEventTriggerHandler.cls
/**
* @name         : MemberUpdateEventTriggerHandler
* @description  : Handler class for Member Update Event platform event.
* <Date>        <Modified By>       <Brief Description of Change>
* 2024-04-17    Siddharth Singh     Created
*/
public class MemberUpdateEventTriggerHandler extends TriggerHandler {
    
    public override void afterInsert() {

        
        Set<Id> newPEEventsMemberIds = new Set<Id>();
        for (Member_Update_Event__e newEvent : (List<Member_Update_Event__e>)Trigger.new) {
            newPEEventsMemberIds.add(newEvent.Member_Id__c);
        }
        System.debug('newPEEventsMemberIds = ' + newPEEventsMemberIds);
        
        if(!newPEEventsMemberIds.isEmpty()){
          System.enqueueJob(new MemberUpdateQueueable(newPEEventsMemberIds, 0));
        }
        
    }
    
    
}