force-app/main/default/objects/Process_Rewards_Event__e/Process_Rewards_Event__e.object-meta.xml
<CustomObject>
    <description>Platform event used as part of Accrual/Purchase process to 1. Issue reward vouchers and 2. Splitting redemption/reward journals</description>
    <label>Process Rewards Event</label>
    <pluralLabel>Process Rewards Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel associated with the Order</description>
    <label>Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Event type: Issue voucher or split redemption journals</description>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Order_Item_No__c.field-meta.xml
<CustomField>
    <fullName>Order_Item_No__c</fullName>
    <label>Order Item No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Program_ID__c</fullName>
    <label>Program ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Total_Debit_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit_Points__c</fullName>
    <label>Total Debit Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Rewards_Event__e/fields/Total_Rewards__c.field-meta.xml
<CustomField>
    <fullName>Total_Rewards__c</fullName>
    <label>Total Rewards</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcessRewardsAction.cls
/**
* @name         : ProcessRewardsAction
* @description  : This invocable action is used to recreate Redemption transaction journals
* @testClass    : TODO -> ProcessRewardsActionTest
* <Date>        <Modified By>     	<Brief Description of Change>
* 2024-04-10    Vince Vuong         Created
* 2024-04-24    Vince Vuong         Updated logic
* 2024-08-15    Nicholas Then.      Updated logic
*/ 
public without sharing class ProcessRewardsAction {

    @InvocableMethod(label='Publish PE for Redemption Rewards')
    public static List<LoyaltyProcessFlowWrapper.FlowOutput> processRewards(List<LoyaltyProcessFlowWrapper.FlowInput> inputs) {

        System.debug('ProcessRewardsAction count = ' + inputs.size());
        System.debug('inputs = ' +  inputs);
        List<Process_Rewards_Event__e> events = new List<Process_Rewards_Event__e>();
        List<LoyaltyProcessFlowWrapper.FlowOutput> outputs = new List<LoyaltyProcessFlowWrapper.FlowOutput>();

        //Initial code - Publish only the first record to the PE , but removed restriction to allow bulk operations eg bulk manual points @ 15Aug
        // for Each Order of Accrual-Purchase, we limit only a single (1) line item/count to publish this event because it carries the SUM of total vouchers to issue
       
        for (LoyaltyProcessFlowWrapper.FlowInput rec : inputs) {
            LoyaltyProcessFlowWrapper.FlowOutput output = new LoyaltyProcessFlowWrapper.FlowOutput();
            events.add(new Process_Rewards_Event__e(
                Member_ID__c = rec.memberId, // previously input[0].memberId
                Program_ID__c = rec.programId,
                Order_No__c = rec.orderId,
                Order_Item_No__c = rec.orderItemId,
                Total_Rewards__c = rec.totalRewards,
                Total_Debit_Points__c = rec.totalPointsToDebit,
                TotalVouchersToIssue__c = rec.totalVouchersToIssue,
                Event_Type__c = rec.eventType,
                Channel__c = rec.channel
            ));

            outputs.add(output);
        }
            System.debug(events);
        if (!events.isEmpty()) {
            // Call method to publish events
            List<Database.SaveResult> results = EventBus.publish(events);

            // Inspect publishing result for each event
            for (Database.SaveResult sr : results) {
                if (sr.isSuccess()) {
                    System.debug('Successfully published event.');
                } else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
                    }
                }
            }
        }
        return outputs;
    }

   

   

    

}